import React from "react";
import Header from "@/components/Header";
import Scrollbar from "@/components/Scrollbar";
import styles from "../styles/404.module.scss";

const custom404 = () => {
  return (
    <>
      <Header LeftComponent={undefined} />
      <Scrollbar />
      <div className={styles["main"]} style={{ textAlign: "center", padding: "20px" }}>

        <h1 style={{ fontSize: "80px", marginTop: "50px" }}>404</h1>
        <h2 style={{ fontSize: "30px" }}>
          Page not found
        </h2>
        <p style={{ fontSize: "20px", marginTop: "20px" }}>
          Looks like you've taken a wrong turn in the KIU Exchange.
        </p>
        <p style={{ fontSize: "20px", marginBottom: "20px" }}>
          Don't worry, just head back to the
          <a href="/"> Homepage </a> and start again.
        </p>
        <img
          src="https://media.giphy.com/media/vnFB72LzHtO4o/giphy.gif"
          alt="Confused guy from Pulp Fiction"
          style={{ width: "500px" }}
        />
        <p style={{ marginTop: "20px" }} >*fun fact: this page was generated by chatGPT!</p>
      </div>
    </>
  );
};

export default custom404;
